const express = require('express'),
      bodyParser = require('body-parser'),
      path = require('path'),
      port = process.env.PORT || 8000,
      app = express();

let data = {};

app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(express.static(path.join(__dirname, 'static')));

app.get('/', function(request, response){
  response.render('index');
})

const server = app.listen(port, () => console.log(`listening ${port}`)),
      io = require('socket.io')(server);

io.on('connection', function(socket) {

  // this code was for testing socket connection
  // socket.emit('greeting', { msg: 'server connection complete' });
  // socket.on('thankyou', function(data) {
  //   console.log(data.msg);
  // });
  socket.on('submit_survey', function(data) {
    socket.emit('updated_message', { message: createMessage(data) });
    socket.emit('lucky_number', { message: luckyNumber() });
  })

});

function createMessage(data) {
  return `You emitted the following information to the server: { name: ${data.name}, location: ${data.location}, language: ${data.language}, comments: ${data.comments}, }`
}

function luckyNumber() {
  return `Your lucky number generated by the server is ${Math.floor(Math.random() * 100 + 1)}`;
}
